sudo: required
services:
  - docker
language: bash
env:
  - dokuwiki_version=2018-04-22c
script:
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
  - docker build --build-arg dokuwiki_version=$dokuwiki_version -t dtroncy/rpi-dokuwiki .
# push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      docker tag dtroncy/rpi-dokuwiki dtroncy/rpi-dokuwiki:$dokuwiki_version
      docker push dtroncy/rpi-dokuwiki:$dokuwiki_version
      docker push dtroncy/rpi-dokuwiki
    fi